version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:14-jdk-buster

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}



  test_with_coverage:
    docker:
      - image: circleci/openjdk:14-jdk-buster
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: participant_db
          POSTGRES_USER: participant_db_user
          POSTGRES_PASSWORD: participant_db_password

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle clean test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_with_coverage:
          requires:
            - build
