version: '3.7'
services:
  postgres-db:
    container_name: local_postgres_participant_db
    image: postgres:10.5
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: participant_db
      POSTGRES_USER: participant_db_user
      POSTGRES_PASSWORD: participant_db_password
